### PR TITLE
fix of validity check following standard

### PR DESCRIPTION
**Pull request by HaHeho**

### CODE REVIEW

**Comment by HaHeho** [comment]
The test probably (apparently) have to be adjusted according to the changes.

I have no experience with Python testing so far. @andresperezlopez  could you look into that? :)

**Comment by andresperezEUT** [comment]
Adapted tests, now 100% coverage on version v0.1.5 (which is now merged into master).

**Comment by HaHeho** [comment]
Thanks for the quick response!

Do you have an idea when this will propagate into the PyPI distribution of the package? Is this according to efforts from your side or limited from another side (no idea how PyPI works so far)?

**Comment by andresperezEUT** [comment]
It is entirely on my side. I will address this problem soon.

**Pull request merged**
